# NumPy 

**NumPy: Librería de álgebra lineal para Python.**

NumPy es el paquete fundamental para la computación científica con Python. Contiene, entre otras cosas:
* un poderoso tipo de datos para matrices N-dimensionales: arreglos numpy
* funciones sofisticadas (broadcast)
* herramientas para integrar código C/C ++ y Fortran
* funcionalidades útiles de álgebra lineal, transformada de Fourier, números aleatorios

Además de sus usos científicos obvios, NumPy también se puede usar como un contenedor multidimensional eficiente de datos genéricos. Se pueden definir tipos de datos arbitrarios. Esto permite a NumPy integrarse de manera rápida y sin problemas con una amplia variedad de bases de datos.

NumPy también es muy rápido (ya que usa librerías de lenguaje C). Para ver más información acerca de por qué usar Arreglos en lugar de Listas, ver [este post de StackOverflow](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).


## Usando NumPy

Una vez se haya instalado NumPy, se puede importar como una librería:

In [0]:
import numpy as np

**En este notebook trabajaremos con:**

* Arreglos NumPy: vectores, matrices
* Funciones para generar arreglos
* Generación de arreglos con números aleatorios
* Métodos y atributos de los arreglos
* Índices en arreglos numpy
* Operaciones con arreglos
* Funciones para trabajar con arreglos


# Arreglos NumPy

Los arreglos de NumPy serán la principal funcionalidad que usaremos durante el curso. 

**Tipos de arreglos:**
* Vectores: 1-d
* Matrices: 2-d (aunque podrían tener una sola fila o una sola columna)



## Creación de Arreglos NumPy (Arrays)

### A partir de Listas de Python 

Podemos crear un Array conviertiendo una lista o lista de listas en un arreglo de NumPy:

In [0]:
lista = [1, 2, 3]
lista

[1, 2, 3]

In [0]:
np.array(lista)

array([1, 2, 3])

In [0]:
arr = np.array(lista)

In [0]:
arr

array([1, 2, 3])

In [0]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [0]:
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Funciones para generar arreglos

Existen varias funciones para generar Arreglos:

## arange

Funciona de forma similar al método "range" de Python pero devuelve un arreglo.

In [0]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [0]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

## ceros y unos (zeros/ones)

Generan arreglos de ceros (zeros) y unos (ones).

In [0]:
np.zeros(3)

array([0., 0., 0.])

In [0]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.zeros(5,5)

TypeError: ignored

In [0]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [0]:
np.zeros((2,3), dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

In [0]:
np.ones(3)

array([1., 1., 1.])

In [0]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## linspace
Retorna un vector (arreglo de una dimensión) desde un número (primer parámetro) hasta otro (segundo parámetro) separados entre si por la misma distancia. El número de elementos está determinado por el tercer parámetro.

In [0]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [0]:
np.linspace?

In [0]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [0]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## eye

Crea una matriz identidad del tamaño indicado en el argumento.

In [0]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Generación de números y arreglos de números aleatorios



Los números aleatorios son importantísimos en computación. Como veremos, NumPy ofrece funciones para generar datos aleatorios simples y basados en algunas distribuciones estadísticas.

## Crear un número aleatorio

Genera números aleatorios con una distribución de probabilidad uniforme en el rango [0, 1).

In [0]:
# Sin argumentos se genera un número aleatorio
np.random.rand()  

0.49251933826526606

### Seed
Semilla para números aleatorios 

In [0]:
np.random.seed(10)

## Crear un arreglo de números aleatorios

Numpy también ofrece varias maneras de crear arreglos de número aleatorios:


### Rand

Crea un arreglo del tamaño dado y lo llena con una muestra aleatoria de números con una distribución uniforme en el rango [0, 1). 

*En la distribución uniforme todos los números reales entre 0 y 1 tienen la misma probabilidad de ocurrencia.*

In [0]:
# Con un número n como argumento se genera un arreglo de números aleatorios de tamaño n 
np.random.rand(5) 

array([0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096])

In [0]:
np.random.rand(5,2) 

array([[0.61252607, 0.72175532],
       [0.29187607, 0.91777412],
       [0.71457578, 0.54254437],
       [0.14217005, 0.37334076],
       [0.67413362, 0.44183317]])

In [0]:
np.random.rand(3,4,2)

array([[[0.43401399, 0.61776698],
        [0.51313824, 0.65039718],
        [0.60103895, 0.8052232 ],
        [0.52164715, 0.90864888]],

       [[0.31923609, 0.09045935],
        [0.30070006, 0.11398436],
        [0.82868133, 0.04689632],
        [0.62628715, 0.54758616]],

       [[0.819287  , 0.19894754],
        [0.8568503 , 0.35165264],
        [0.75464769, 0.29596171],
        [0.88393648, 0.32551164]]])

### Randn
Retorna un arreglo con una muestra de números aleatorios con una distribución normal (centrada en 0), a diferencia de rand cuya distribución es uniforme:


![wget](https://drive.google.com/uc?export=view&id=1RRx5wqZeknAOTTUggdyeq0s7eOkptZDV)

In [0]:
np.random.randn(5)

array([-0.36225179, -1.12913125, -0.34971048, -1.05272652,  1.28227668])

In [0]:
np.random.randn(4,5)

array([[-0.17180538,  0.57765806, -1.47497488,  0.07878845,  0.91841365],
       [-0.49269736,  0.09646237, -0.65275994, -0.22176244, -1.06828657],
       [-1.22769205, -1.79857302, -0.68520734, -1.40986887,  1.25239859],
       [ 0.46956276,  0.32692165,  1.80854321, -1.413068  ,  2.52330509]])

Más info acerca de distribuciones de probabilidad en este [**enlace**](https://www.healthknowledge.org.uk/public-health-textbook/research-methods/1b-statistical-methods/statistical-distributions). 

### Randint
Retorna números enteros aleatorios desde el primer parámetro (inclusive) hasta el segundo parámetro (excluido). Si tiene un tercer argumento, éste será el número de elementos que tendrá el arreglo de enteros aleatorios que retorna.

In [0]:
# El primer parámetro es el límite inferior, 
# el segundo el límite superior
# el tercero es el número de elementos. Por defecto es 1
np.random.randint(1,100) 

74

In [0]:
np.random.randint(90,100,(3,4))

array([[92, 99, 90, 99],
       [93, 96, 92, 99],
       [92, 95, 99, 90]])

## Importar directamente función de un módulo

Para evitar tener que llamar el módulo y luego la función, por ejemplo:

**np.random**

Se puede importar la función directamente.

In [0]:
from numpy.random import randint, randn

In [0]:
randint(500,1000)

600

# Atributos y manipulación de los arreglos


In [0]:
arr = np.arange(6)
ranarr1 = np.random.randint(0,50,10)
ranarr2 = np.random.randint(0,50,(10,10))

In [7]:
arr

array([0, 1, 2, 3, 4, 5])

In [0]:
ranarr1

array([47,  6,  6, 15, 18, 38, 23, 43,  0, 34])

In [0]:
ranarr2

array([[ 5, 26, 26, 26, 35, 39, 42, 40, 32, 18],
       [31, 25,  5, 19,  7, 22,  2,  0, 39,  6],
       [17, 39,  3, 15, 41, 34, 28, 19, 19, 30],
       [22, 28, 10, 19, 13,  4,  0, 12,  3, 22],
       [ 6, 45, 26, 22, 43, 36,  6, 35, 24, 48],
       [11,  8,  8,  3, 22, 44, 13, 31, 39, 48],
       [29, 47, 24, 30,  5,  5, 13,  9,  7, 48],
       [23,  3, 30, 21, 10, 33, 28, 42,  1, 25],
       [35, 47, 16, 27, 37,  9,  7, 30, 39, 32],
       [19, 23, 44, 29, 11,  6, 28, 38, 47, 37]])

## Dimesionalidad del arreglo

In [0]:
arr.ndim

1

In [0]:
ranarr2.ndim

2

## Shape: Forma del arreglo

Shape  es un atributo de los arreglos que indica las dimensiones del arreglo:

In [0]:
# Vector: 1-dimensión
arr.shape

(6,)

In [0]:
ranarr2.shape

(10, 10)

In [8]:
arr

array([0, 1, 2, 3, 4, 5])

## Reshape
Retorna un arreglo que contiene los mismos datos que el arreglo original pero con unas dimensiones nuevas.

In [0]:
arr = arr.reshape(2,3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [0]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [9]:
# Debe contener el mismo número de elementos que el arreglo original. 
# De lo contrario, se produce un error como aquí:
arr.reshape(6, 2)


ValueError: ignored

## max, min, argmax, argmin

Estos métodos se usan para encontrar los valores máximos y mínimos en un arreglo. También, para encontrar los índices donde están ubicados mediante argmin/argmax.

In [10]:
ranarr1

array([31, 17, 17, 37, 11, 45, 43, 41,  6, 45])

In [11]:
ranarr1.max()

45

In [12]:
ranarr1.argmax() # Busca el indice del valor max

5

In [0]:
ranarr1.min()

0

In [0]:
ranarr1.argmin()

1

In [0]:
ranarr2

array([[ 9, 26, 30, 48, 48, 28, 36,  8, 10, 31],
       [26, 43, 31, 20, 12, 22,  4, 46, 39, 18],
       [39, 43, 34, 25, 35, 38, 29, 14, 27,  6],
       [19, 44, 35, 42,  6, 29, 24,  1, 45, 43],
       [34, 44, 22, 14, 25, 44, 39, 19, 35, 43],
       [21, 10, 46, 44, 49,  6, 27, 23, 49, 30],
       [17, 24, 11, 43, 21, 10, 24, 10, 13,  8],
       [47, 26, 25, 31, 17, 23, 16, 10, 34, 13],
       [26, 18, 13,  1, 30,  6, 29,  2, 41, 46],
       [35,  6, 46, 38, 22, 39, 38, 38, 15, 11]])

In [0]:
ranarr2.max()

49

In [0]:
ranarr2.max(axis=0) #axis=0 por columna

array([47, 44, 46, 48, 49, 44, 39, 46, 49, 46])

In [0]:
ranarr2.argmax(axis=0) # Busca el indice

array([7, 3, 5, 0, 5, 4, 4, 1, 5, 8])

In [0]:
ranarr2.max(axis=1) #axis=0 por fila

array([43, 45, 41, 39, 49, 48, 48, 43, 45, 48])

## dtype

También es posible averiguar el tipo de dato del arreglo usando el atributo dtype:

In [0]:
arr.dtype

dtype('int64')

# NumPy Índices

En un arreglo el índice es la posición de la secuencia para cada uno de los elementos.

In [0]:
arreglo1 = np.array([100,101,102,103,104,105,106,107,108,109,110])
print(arreglo1)


[100 101 102 103 104 105 106 107 108 109 110]


### Arreglos uni-dimesionales Vectores

La forma más sencilla de seleccionar un elemento o un conjunto de ellos de un arreglo es muy similar a las listas de Python:

In [0]:
# Obtiene el elemento ubicado en el índice dado
arreglo1[8]

108

In [0]:
# Obtiene los elementos en el rango dado (sin incluir el límite superior)
arreglo1[1:5]

array([101, 102, 103, 104])

In [0]:
# Obtiene los elementos desde el inicio hasta el elemento en la posición 7
arreglo1[:7]

array([100, 101, 102, 103, 104, 105, 106])

In [0]:
# Obtener desde una posición hasta el final del arreglo
arreglo1[5:]


array([105, 106, 107, 108, 109, 110])

In [0]:
# Obtener desde la posición inicial y hasta la 8, cada 2 posiciones
arreglo1[0:8:2]

array([100, 102, 104, 106])

In [0]:
# Obtener el último elemento del arreglo
arreglo1[-1]

110

In [0]:
# Obtener todo el arreglo pero en orden inverso
arreglo1[::-1]

array([110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

### Arreglos bi-dimensionales (Matrices)

In [0]:
matriz_a = np.array([[1,3],[2,8]])
print(matriz_a)

[[1 3]
 [2 8]]


In [0]:
#Obtener el elemento de la primera fila y primera columna
matriz_a[0,0]

1

In [0]:
#Obtener el elemento de la última fila y última columna
matriz_a[1,1]

8

In [0]:
#Obtener todos los elementos de la primera fila
print(matriz_a[0,:])

[1 3]


In [0]:
#Obtener todos los elementos de la primera columna
print(matriz_a[:,0])

[1 2]


In [0]:
# Inicialización
arr2d = np.zeros((5,5))
for i in range(5):
    arr2d[i,0] = i
    arr2d[i,1] = i*2
    arr2d[i,2] = i*3
    arr2d[i,3] = i*4
    arr2d[i,4] = i*5
    
arr2d

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 2.,  4.,  6.,  8., 10.],
       [ 3.,  6.,  9., 12., 15.],
       [ 4.,  8., 12., 16., 20.]])

In [0]:
# Traer la matriz 2x2 de la esquina inferior derecha
arr2d[3:,3:]

array([[12., 15.],
       [16., 20.]])

### Arreglo n-dimensionales (Tensores)


El formato general es **arr_nd[d1][d2][dn]** o **arr_2d[d1,d2,dn]**. 

Por claridad, se recomienda la notación con coma.

In [0]:
arr_3d = np.array(([[[5, 10], [20, 25]], [[7, 21], [7, 28]]]))
print(arr_3d)

[[[ 5 10]
  [20 25]]

 [[ 7 21]
  [ 7 28]]]


In [0]:
# Accediendo a un elemento particular
arr_3d[0, 0, 0]

5

In [0]:
# Tomar el primer elemento de la primera dimesión (Es decir, la primera matriz)
arr_3d[0,:,:]


array([[ 5, 10],
       [20, 25]])

In [0]:
# Traer la primera fila de las 2 submatrices
arr_3d[:,0,:]

array([[ 5, 10],
       [ 7, 21]])

In [0]:
# Traer la última fila de las 2 submatrices
arr_3d[:,-1,:]

array([[20, 25],
       [ 7, 28]])

### "Indexado elegante" (fancy indexing)

Se permite indexar filas o columnas enteras de una sola vez:

In [0]:
arr = np.arange(100,121)
arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120])

In [0]:
# Obtener elementos también en cualquier orden
arr[[7, 3, 4, 2]]

array([107, 103, 104, 102])

In [0]:
# matriz
arr2d = np.zeros((10,10))

arr2d

In [0]:
# Tamaño de la columna
arr_length = arr2d.shape[1]
arr_length

5

In [0]:
# Inicialización

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [0]:
# Obtener elementos de la matriz en cualquier orden
arr2d[[1,4,2],:]

array([[1., 1., 1., 1., 1.],
       [4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2.]])

In [0]:
arr2d[:,[1,4,2]]

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

## Selección condicional


In [0]:
arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120])

In [0]:
#Validación elemento a elemento
indices_cond = arr > 114
indices_cond

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True])

In [0]:
# Seleccion de elementos basados en alguna condición
arr[indices_cond]

array([115, 116, 117, 118, 119, 120])

In [0]:
arr[arr>114]

array([115, 116, 117, 118, 119, 120])

In [0]:
#Usando condiciones más complejas
arr[(arr>112) & (arr<118)]

array([113, 114, 115, 116, 117])

In [0]:
np.where(arr>116)

(array([17, 18, 19, 20]),)

In [0]:
np.where(arr>116,1,-1)

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        1,  1,  1,  1])

# NumPy  - Operaciones


## Aritméticas

Es posible hacer operaciones aritméticas entre arreglos; y también, entre arreglos y escalares. Se usan los operadores aritméticos tradicionales.

### Operaciones con vectores

In [0]:
v1 = np.array([2,10,10])
print(v1)

In [0]:
#Multiplicación vector por escalar
print(2*v1)

In [0]:
#Suma de dos vectores
v2 = np.array([1,2,1])
print(v1)
print(v2)


In [0]:
# suma
print(v1+v2)

In [0]:
# resta
print(v1-v2)

In [0]:
# multiplicación
print(v1*v2)

In [0]:
# división
print(v1/v2)

In [0]:
# Creamos arr para el siguiente ejemplo
arr = np.arange(0,10)

arr

In [0]:
# En Python, la siguiente división retorna un error
1/0

In [0]:
# Sin embargo, en NumPy si dividimos arr/arr, obtendremos un Warning de división por cero, pero no se considera como un error! 
# Se reemplaza por 'NaN' (Not a Number)

arr/arr

In [0]:
# 1/arr también produce un warning, pero no un error. En la división 1/0 se obtiene 'inf' (infinito)
1/arr

In [0]:
# Potencia
arr**3

In [0]:
np.concatenate((arr,arr))

#### Diferencia con las listas de Python 

In [0]:
# Listas
lista = [1, 2] 
lista2 = [3, 4]

In [0]:
lista + lista2

In [0]:
lista*5

In [0]:
# Intersección de conjuntos de Python
{1,2,4} & {3,4}

 ### Operaciones con Matrices

#### Suma/Resta de matrices

In [0]:
a = np.array([[1,1,1], [2,2,2]]) # arreglo 2 x 3

b = np.array([[0, 1, 2], [3, 4, 5]]) # arreglo 2 x 3

print(a)
print()
print(b)

In [0]:
print(a+b)

In [0]:
print(a-b)

#### Multiplicación de Matrices

In [0]:
a = np.array([[1, 0], [2, -1]])
print(a)
print()
b = np.array([[1, 1], [2, 2]])
print(b)


In [0]:
# Para el producto punto se usa dot()
print(np.dot(a, b))

In [0]:
#Producto entre la misma matriz
print(np.dot(a, a))

#### Multiplicación (elemento a elemento) entre matrices

In [0]:
# El operador * multiplica los elementos uno a uno (NO es multiplicación matricial)
print(a*b)

In [0]:
matriz_2x3 = np.ones((2,3))
print(matriz_2x3)

In [0]:
print(a/matriz_2x3)
# En Python, esta división retorna un error porque no tienen las mismas dimensiones

### Broadcasting

Los arreglos de Numpy se diferencian de las listas de Python porque tienen la habilidad de hacer "broadcast":

In [13]:
c = np.zeros((3, 3))
print(c)
print(c.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)


In [14]:
n = np.array([1, 2, 3]).reshape(3,1)
print(n)
print(n.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [15]:
t = n + c  # Se expande la primera dimensión de n
print(t)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [0]:
arr = np.arange(1,11)
print(arr)

In [0]:
# También, se puede asignar un valor dado a un rango de índices en un arreglo (Broadcasting)
arr[0:5]=100

# Resultado
arr

In [0]:
arr[0::2]=-1

arr

In [0]:
# Recuperar el arreglo anterior
arr = np.arange(0,11)

# Resultado
arr

In [0]:
# Troceado de arreglos
trozo_de_arr = arr[0:6]

# Resultado
trozo_de_arr

In [0]:
# Cambios 
trozo_de_arr[:]=99

#Show Slice again
trozo_de_arr

**OJO: los cambios también ocurren en el arreglo original!**

In [0]:
arr

**Los datos no se copian, un "trozo" de un arreglo es simplemente una vista del arreglo original!** Esto sirve para prevenir problemas de memoria!

In [0]:
# Para obtener una copia, es necesario usar el método copy()
copia_arr = arr[7:].copy()

copia_arr

In [0]:
copia_arr[:] += 100

copia_arr

In [0]:
arr

### Otras operaciones


In [0]:
a = np.array([[0, 1, 2], [3, 4, 5]]) # arreglo 2 x 3
a

In [0]:
a.transpose()

In [0]:
a

In [0]:
a.sum()

In [0]:
a.sum(axis=0)

In [0]:
a.mean(axis=0)

In [0]:
a.std()

# NumPy  - Funciones

* Funciones Universales
* Iterando sobre los arreglos

## Funciones Universales con Arreglos

Numpy viene con muchas [funciones universales para arreglos](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), las cuales son operaciones matemáticas que se pueden usar para efectuar una operación sobre el arreglo. Por ejemplo:

### Cálculos sobre el arreglo

In [0]:
arr = np.array([2,6,1,10])
arr

In [0]:
# Raíz cuadrada elemento a elemento
np.sqrt(arr)

In [0]:
# exponencial (e^)
np.exp(arr)

In [0]:
# Funciones trigonométricas
np.sin(arr)

In [0]:
# Logaritmo natural
np.log(arr)

### Reducciones Básicas

In [0]:

vector = np.random.randint(0,100,10)
print(vector)

**Máximo**

In [0]:
np.max(vector) # igual que arr.max()

**Mínimo**

In [0]:
np.min(vector)

**Suma de todos los elementos**

In [0]:
np.sum(vector)

**Promedio**

In [0]:
np.mean(vector)

**Desviación estándar**

In [0]:
np.std(vector)

## Iterando sobre arreglos

In [16]:
# Arreglo 1-D
arr = np.arange(0,4)
arr

array([0, 1, 2, 3])

In [17]:
# Iterando sobre un arreglo unidimensional
for item in arr:
    print(item)

0
1
2
3


In [18]:
# Arreglo 2-D
arr = np.arange(0,4).reshape(2,2)
arr

array([[0, 1],
       [2, 3]])

In [19]:
# Iterando por filas sobre un arreglo 2-D
for fila in arr:
    print(fila)

[0 1]
[2 3]


In [20]:
# Si se quiere hacer una operación sobre cada uno de los valores, es necesario usar la propiedad "flat"
for item in arr.flat:
    print(item)

0
1
2
3


In [23]:
# Iterar sobre el par de coordenadas x,y
a = np.array([[1,2],[3,4],[5,6]])
print(a)


[[1 2]
 [3 4]
 [5 6]]


In [22]:
for (i, j), value in np.ndenumerate(a):
  print('Fila:', i, 'Col:', j, 'Valor:', value)

Fila: 0 Col: 0 Valor: 1
Fila: 0 Col: 1 Valor: 2
Fila: 1 Col: 0 Valor: 3
Fila: 1 Col: 1 Valor: 4
Fila: 2 Col: 0 Valor: 5
Fila: 2 Col: 1 Valor: 6


In [0]:
np.ndenumerate?

**Consultar más info: https://docs.scipy.org/doc/numpy/user/quickstart.html**